apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
      - name: preprocessing-container
        image: preprocessing-service:latest
        ports:
        - containerPort: 8080